### ISSUE TITLE
No Video

### ISSUE THREAD

**Issue by hank** [elad-bar/ha-custom-components#3]
I believe I have the component working - I have camera.bi_all and such listed, as expected. The issue is that I cannot get any video displayed from the cameras. The proxy stream it creates is:

https://hass/api/camera_proxy_stream/camera.bi_all?token=ad1...

This just spins and is blank, and there are no log messages I can find about what might not be working. I know the credentials and hostname/port are correct. Let me know how I can debug. Thanks!

**Comment by elad-bar** [comment]
Can you check if you can access the following URL through VLC:
HTTP://[IP]:[PORT]/h264/[camera_id]/temp.m3u8

Replace [IP] with the IP or hostname that you are using in HA
Replace [PORT] with the port that you are using in HA
Replace [camera_id] with one of the camera id that you are using in HA

**Comment by hank** [comment]
When I go there I get a login prompt, and if I authenticate it attempts to download the file.

**Comment by elad-bar** [comment]
through VLC Player?

**Comment by hank** [comment]
In VLC it fails to play because it receives the login webpage HTML. Do I have to disable web authentication to make this work?

**Comment by elad-bar** [comment]
I disabled it for local network, I!ll try to set the auth always as configured in your system to reproduce... I will update you

**Comment by elad-bar** [comment]
Pushed new version v1.0.3 of BlueIris component with the fix, I didn't encounter it since I'm using authenticated "non-LAN only" requests, I guess you are using "All connections"

**Comment by hank** [comment]
Thanks! It works now. Notably I had to go to Blue Iris web server settings, then set the dropdown to only require authentication from Non-LAN sources (one could also just uncheck the secure session box completely, but be careful about exposing the server outside your LAN!). Then I did this:

```yaml
  - cards:
      - camera_image: camera.bi_all
        entities:
          - camera.bi_all
        type: picture-glance
    badges: []
    title: Cameras
    path: cameras
    panel: true```

Works great!!
