### ISSUE TITLE
Typos in blueiris.json

### ISSUE THREAD

**Issue by darkgrue** [elad-bar/ha-custom-components#4]
There appears to be a typo in the blueiris.json manifest in both `ha-custom-components/blueiris.json` and `ha-blueiris/blue_iris.json`. Also, the version number of the manifests are out-of-sync, even though they point to the same set of files.

Line 17 reads:
```
            "https://raw.githubusercontent.com/elad-bar/ha-custom-components/master/custom_components/blueiris/witch.py"
```
and probably should read (the 's' from 'switch' is missing):
```
            "https://raw.githubusercontent.com/elad-bar/ha-custom-components/master/custom_components/blueiris/switch.py"

**Comment by elad-bar** [comment]
Fixed, thanks
